#version: '3.9'

services:
  
  aws_db:
    image: postgres:alpine
    ports:
      -  5432:5432 # ${DB_PORT}:5432
    container_name: aws_db #${DB_HOST}
    restart: always
    environment:
          - POSTGRES_USER=postgres #${DB_USERNAME}
          - POSTGRES_PASSWORD=1q2w3e4r #${DB_PASSWORD}
          - POSTGRES_DB=aws_db #${DB_DATABASE}
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - aws-network

  app:
    
    ports:
      - 300:3000 #${APP_PORT}:3001
    networks:
      - aws-network
    container_name: aws_app
    environment:
          - DB_USERNAME=postgres #${DB_USERNAME}
          - DB_PASSWORD=1q2w3e4r #${DB_PASSWORD}
          - DB_DATABASE=aws_db #${DB_DATABASE}
          - DB_HOST=localhost
          - DB_PORT=5432
    
    links:   #Novo atributo incluso
      - aws_db
    depends_on:
      - aws_db

    build:
      context: .
      dockerfile: Dockerfile
  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: aws_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: lglmoura@gmail.com #${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: 1q2w3e4r #${PGADMIN_PASSWORD}
    ports:
      - '8080:80'

    links:   #Novo atributo incluso
      - aws_db
    depends_on:
      - aws_db

    networks:
      - aws-network
  
networks:
  aws-network:
    driver: bridge
volumes:
  pg-data:
